name: Release

on:
  push:
    branches:
      - master
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: npm config set registry https://registry.npmjs.org    
      - run: npm ci
      - run: npm install semantic-release
      #- run: npm run build
      #- run: npm set //registry.npmjs.org/:_authToken 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
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GIT_TOKEN }}
          NPM_TOKEN: ${{ secrets.RELEASE_NPM_TOKEN }}


    
